name: webrtc-eyestalk Actions

on: [push]
jobs:        
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Version tag
        uses: Jorricks/action-python-autotagging@1.0.1

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: src/your_package/__init__.py
          variable: __version__
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: kimnamju/webrtc-eyestalk-back      
      
      -
        name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: kimnamju/webrtc-eyestalk-back:latest, kimnamju/webrtc-eyestalk-back:${{ steps.version-bump.outputs.newTag }}
