name: webrtc-eyestalk Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
		name: Log in to Docker Hub
		uses: docker/login-action@v1.10.0
		with:
		  username: ${{ secrets.DOCKERHUB_USERNAME  }}
		  password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
	    name: Extract metadata (tags, labels) for Docker
        id: meta
		uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
		with:
		  images: kimnamju/webrtc-eyestalk-back
      - 
	    name: Build and push Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
		  file: ./Dockerfile
          push: true
          tags: kimnamju/webrtc-eyestalk-back:latest, kimnamju/webrtc-eyestalk-back:${{ steps.version-bump.outputs.newTag }}
