name: webrtc-eyestalk Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      -
        name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae8x65ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: kimnamju/webrtc-eyestalk-back    
      
      -
        name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: ./Dockerfile 
          push: true
          tags: kimnamju/webrtc-eyestalk-back:latest, kimnamju/webrtc-eyestalk-back:${{ steps.version-bump.outputs.newTag }}
